### ISSUE TITLE
Sizer4 localization request

### ISSUE THREAD

**Issue by l3xrom** [wvxwxvw/translation#1]
Доброго времени суток!

Вы не могли бы поделиться русификатором или русской версией [Sizer4](http://www.brianapps.net/sizer4/), если у вас осталась.

На ру-борде ссылка от вас сдохла и вас там давно не было, поэтому не нашёл способа лучше как попросить здесь.

И спасибо большое за ваши локализации! Уже не один раз встречал в официальных установщиках софтов, что на русский переведено именно вами.

**Comment by wvxwxvw** [comment]
[sizer4_dev640_RUS.zip](https://github.com/wvxwxvw/translation/files/9636891/sizer4_dev640_RUS.zip)  
  
Переведен сам исполняемый файл. Меню появляется при кликах ПКМ на краях окон (вроде всегда) и на кнопках свернуть/максимизировать (только если кнопки от Windows, а не от скина целевой программы). Сейчас проверял на Win7, но раньше он и на 8-8.1 у меня работал.

**Comment by l3xrom** [comment]
@wvxwxvw огромное спасибо!
