### ISSUE TITLE
file menu tools 8

### ISSUE THREAD

**Issue by g0blin-NN** [wvxwxvw/translation#2]
ждем правильный перевод. спасибо.

**Comment by wvxwxvw** [comment]
Добавил. На Win 7 у ярлыков подменю FileMenu Tools дублируется и в папке установки каша из файлов двух версий. Сказал бы кто автору.

**Comment by g0blin-NN** [comment]
была бы она у меня эта win7. это скрины делать нужно на проблему. в win10 нормально. а связь через support@lopesoft.com я другой не знаю.
спасибо за перевод.

**Comment by g0blin-NN** [comment]
8.1.0 появилась. в основном там для windows 11 правки.

**Comment by wvxwxvw** [comment]
Проверяйте. Сам ставить не буду, 8-я линейка не работает толком на Win7.
